import Head from 'next/head'
import { Navbar } from '../components/Navbar';
import { Button } from 'react-bootstrap'
import { useAuth } from '../context/AuthContext'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import BlackJack from '../components/BlackJack/BlackJack'
import AccountForm from '../components/Forms/AccountForm';

export default function Home() {
  const { user, logOut } = useAuth()
  const [accountFormVisable, setAccountFormVisable] = useState(false)
  const [shownGame, setShownGame] = useState('')
  const [isSignup, setIsSignup] = useState(false)

  function handleShowLogIn(){
    setLogInVisiable(true)
    setSignUpVisable(false)
  }

  function handelShowGameChange(newShownGame){
    setShownGame(newShownGame)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar changeShownGame={handelShowGameChange}/>
      <div className={styles.container}>
        <main className='border border-danger'>
          {user ? (
            <>
            <div className='container border border-primary h-0'>
              {shownGame === 'BlackJack' ? <BlackJack changeShownGame={handelShowGameChange} /> : null}
            </div>
            </>
            
          ) : (
            <>
              <Button  varient="primary" onClick={() => (setIsSignup(false), setAccountFormVisable(true))}>Login</Button>
              <Button  variant="success" onClick={() => (setIsSignup(true), setAccountFormVisable(true))}>Signup</Button>
              {accountFormVisable ?  <AccountForm handleShowAccountForm={setAccountFormVisable} setIsSignup={setIsSignup} isSignup={isSignup} />: null}
            </>
            
          )}
        </main>
      </div>
  </>
  )
}
